// This comment simulates the import of types generated by Supabase or similar tools.
// These types (Database, Tables, TablesInsert, Enums, Constants) are assumed to be globally available
// or imported from a central types definition file as per the problem description.
// import type { Database, Tables, TablesInsert, Enums, Constants } from "./supabase"; // Actual import path

import { Enums, Tables, TablesInsert } from './database.types';

// --- Helper Types ---

/**
 * Represents a GeoJSON Point object.
 * Used for facility locations, as the database model specifies 'unknown' for the 'location' field.
 */
export type GeoJsonPoint = {
  type: 'Point';
  coordinates: [number, number]; // [longitude, latitude]
};

// --- Sports DTOs ---

/**
 * DTO for a sport.
 * Corresponds to GET /sports and GET /sports/{sport_id} responses.
 * Directly maps to the `sports` table row.
 */
export type SportDto = Omit<Tables<'sports'>, 'min_duration_minutes' | 'max_duration_minutes' | 'duration_step_minutes'>;

// --- Facilities DTOs ---

/**
 * DTO for a simplified sport representation, used within FacilityListItemDto.
 */
export type SupportedSportShortDto = Pick<Tables<'sports'>, 'id' | 'name'>;

/**
 * DTO for a facility item in a list.
 * Corresponds to an item in the `items` array of GET /facilities response.
 */
export type FacilityListItemDto = Pick<
  Tables<'facilities'>,
  | 'id'
  | 'osm_id'
  | 'name'
  | 'surface_type'
  | 'addr_city'
  | 'addr_street'
  | 'addr_housenumber'
> & {
  location: GeoJsonPoint;
  main_photo_url: string | null; // Derived: URL of the primary photo
  supported_sports: SupportedSportShortDto[]; // Derived: List of sports available at the facility
};

/**
 * DTO for the paginated list of facilities.
 * Corresponds to the GET /facilities response.
 */
export type FacilitiesListResponseDto = {
  items: FacilityListItemDto[];
  total: number;
  limit: number;
  offset: number;
};

/**
 * DTO for a facility photo's details, used in FacilityDetailDto.
 * Note: `caption` and `sort_order` are from the API plan, not directly in `facility_photos` table schema.
 */
export type FacilityPhotoDetailDto = Pick<Tables<'facility_photos'>, 'id'> & {
  url: string; // Derived: Public URL of the photo
  caption: string | null;
  sort_order: number;
};

/**
 * DTO for detailed information about a sport supported by a facility.
 * Used in `FacilityDetailDto`.
 */
export type SupportedSportDetailDto = Pick<
  Tables<'sports'>,
  | 'id'
  | 'parent_sport_id'
  | 'name'
  | 'created_at'
  | 'updated_at'
>;

/**
 * DTO for detailed facility information.
 * Corresponds to the GET /facilities/{facility_id} response.
 * `sport_osm_tags` corresponds to the `sport` column in the `facilities` table.
 * `way_geometry` is omitted by default as per API plan suggestion but can be added if needed.
 */
export type FacilityDetailDto = Omit<
  Tables<'facilities'>,
  'location' | 'way_geometry' | 'sport' // `location` replaced with GeoJsonPoint, `sport` with `sport_osm_tags`
> & {
  location: GeoJsonPoint;
  sport_osm_tags: Tables<'facilities'>['sport']; // Mapping `sport` column to `sport_osm_tags`
  photos: FacilityPhotoDetailDto[];
  supported_sports_details: SupportedSportDetailDto[];
  // way_geometry?: Tables<"facilities">["way_geometry"]; // Can be included if needed by client
};

/**
 * DTO for a busy slot in facility availability.
 * Used in `FacilityAvailabilityResponseDto`.
 */
export type FacilityAvailabilitySlotDto = Pick<
  Tables<'reservations'>,
  'start_time' | 'end_time'
>;

/**
 * DTO for facility availability response.
 * Corresponds to GET /facilities/{facility_id}/availability response.
 */
export type FacilityAvailabilityResponseDto = {
  facility_id: Tables<'facilities'>['id'];
  sport_id: Tables<'sports'>['id'];
  requested_start_date: string; // Format: YYYY-MM-DD
  requested_end_date: string; // Format: YYYY-MM-DD
  busy_slots: FacilityAvailabilitySlotDto[];
};

// --- Facility Photos DTOs ---

/**
 * DTO for a facility photo item in a list.
 * Corresponds to an item in the `items` array of GET /facilities/{facility_id}/photos response.
 * Note: `caption` and `sort_order` are from the API plan.
 */
export type FacilityPhotoListItemDto = Pick<
  Tables<'facility_photos'>,
  'id' | 'storage_path' | 'created_at'
> & {
  url: string; // Derived: Public URL of the photo
  sort_order: number;
  caption: string | null;
};

/**
 * DTO for the paginated list of facility photos.
 * Corresponds to the GET /facilities/{facility_id}/photos response.
 */
export type FacilityPhotosListResponseDto = {
  items: FacilityPhotoListItemDto[];
  total: number;
  limit: number;
  offset: number;
};

// --- Reservations Command Models and DTOs ---

/**
 * Command Model for creating a new reservation.
 * Corresponds to the request body of POST /reservations.
 */
export type CreateReservationCommand = Pick<
  TablesInsert<'reservations'>,
  'facility_id' | 'sport_id' | 'start_time' | 'end_time'
>;

/**
 * DTO for basic facility details, optionally included in reservation responses.
 */
export type ReservationFacilityDetailsDto = {
  name: Tables<'facilities'>['name'];
  address_line: string; // Derived: e.g., "Ulica Testowa 10, Kraków"
};

/**
 * DTO for basic sport details, optionally included in reservation responses.
 */
export type ReservationSportDetailsDto = Pick<Tables<'sports'>, 'name'>;

/**
 * DTO for a reservation.
 * Corresponds to the response of POST /reservations.
 * `organizer_id` is the `user_id` from the `reservations` table.
 * `invitation_token` is a generated token, not in the database table.
 */
export type ReservationDto = Pick<
  Tables<'reservations'>,
  | 'id'
  | 'facility_id'
  | 'sport_id'
  // user_id from DB is represented as organizer_id
  | 'start_time'
  | 'end_time'
  | 'status'
  | 'created_at'
  | 'updated_at'
> & {
  organizer_id: Tables<'reservations'>['user_id'];
  invitation_token: string;
  facility_details?: ReservationFacilityDetailsDto;
  sport_details?: ReservationSportDetailsDto;
};

/**
 * DTO for a reservation item in the user's list of reservations.
 * Corresponds to an item in the `items` array of GET /me/reservations response.
 * Contains denormalized data for list display.
 */
export type UserReservationListItemDto = Pick<
  Tables<'reservations'>,
  | 'id'
  | 'facility_id'
  | 'sport_id'
  // user_id from DB is represented as organizer_id
  | 'start_time'
  | 'end_time'
  | 'status'
> & {
  facility_name: Tables<'facilities'>['name'];
  facility_main_photo_url: string | null; // Derived
  sport_name: Tables<'sports'>['name'];
  organizer_id: Tables<'reservations'>['user_id'];
  invitation_token: string; // Matches ReservationDto
  is_organizer: boolean;
  participants_count?: number; // Optional as per API plan
};

/**
 * DTO for the paginated list of user's reservations.
 * Corresponds to the GET /me/reservations response.
 */
export type UserReservationsListResponseDto = {
  items: UserReservationListItemDto[];
  total: number;
  limit: number;
  offset: number;
};

/**
 * DTO for a reservation participant.
 * Used in `ReservationDetailDto`.
 * `reservation_participants` table is not in the provided DB schema,
 * so `user_id` and `joined_at` are typed as `string`.
 * `display_name` and `avatar_url` come from the `profiles` table.
 */
export type ReservationParticipantDto = {
  user_id: Tables<'profiles'>['id'];
  display_name: Tables<'profiles'>['display_name'];
  avatar_url: Tables<'profiles'>['avatar_url'];
  joined_at: string; // timestampz, from hypothetical reservation_participants.joined_at
};

/**
 * DTO for detailed reservation information.
 * Corresponds to the GET /reservations/{reservation_id} response.
 */
export type ReservationDetailDto = Pick<
  Tables<'reservations'>,
  | 'id'
  | 'facility_id'
  | 'sport_id'
  // user_id from DB is represented as organizer_id
  | 'start_time'
  | 'end_time'
  | 'status'
  | 'created_at'
  | 'updated_at'
> & {
  organizer_id: Tables<'reservations'>['user_id'];
  organizer_display_name: Tables<'profiles'>['display_name'];
  invitation_token: string; // Matches ReservationDto
  facility_details?: ReservationFacilityDetailsDto; // As in ReservationDto
  sport_details?: ReservationSportDetailsDto; // As in ReservationDto
  participants: ReservationParticipantDto[];
};

/**
 * DTO for the response after cancelling a reservation.
 * Represents the updated reservation object with status "CANCELLED".
 * Uses ReservationDto and narrows the status.
 */
export type CancelReservationResponseDto = ReservationDto & {
  status: Extract<Enums<'reservation_status_enum'>, 'cancelled'>;
};

/**
 * DTO for reservation details fetched by an invitation token.
 * Corresponds to GET /reservations/by-token/{invitation_token} response.
 * Contains minimal, publicly accessible information.
 */
export type ReservationByTokenDto = Pick<
  Tables<'reservations'>,
  'id' | 'start_time' | 'end_time'
> & {
  facility_name: Tables<'facilities'>['name'];
  facility_address: string; // Derived: e.g., "Orlik..., Ulica Testowa 10, Kraków"
  sport_name: Tables<'sports'>['name'];
  organizer_display_name: string | null; // Potentially partial, e.g., "John D."
  participants_count: number;
  requires_login_to_join: boolean;
};

/**
 * DTO for a participant who just joined a reservation.
 * Used in `JoinReservationResponseDto`.
 */
export type JoinedParticipantDto = {
  user_id: Tables<'profiles'>['id'];
  display_name: Tables<'profiles'>['display_name'];
  joined_at: string; // timestampz, from hypothetical reservation_participants.joined_at
};

/**
 * DTO for the response after joining a reservation.
 * Corresponds to POST /reservations/{reservation_id}/join response.
 */
export type JoinReservationResponseDto = {
  message: string;
  participant: JoinedParticipantDto;
};

// --- Tasks DTOs ---

/**
 * DTO for the response of the task to send reservation reminders.
 * Corresponds to POST /tasks/send-reservation-reminders response.
 */
export type TaskSendReservationRemindersResponseDto = {
  status: 'success' | 'failure';
  reminders_sent?: number;
  error?: string;
};
